import { Complaint, User, NotificationItem } from '../types';

export const INITIAL_USERS: (User & { password?: string })[] = [
  {
    id: 'usr-admin-1',
    name: 'Panchayat Officer Rajesh Shinde',
    email: 'admin@grampanchayat.gov.in',
    mobile: '9876543210',
    address: 'Gram Panchayat Bhavan, Main Road, Ward 1',
    role: 'ADMIN',
    password: 'Admin@123',
    createdAt: '2026-01-01T08:00:00Z',
    unreadNotificationsCount: 3,
  },
  {
    id: 'usr-cit-1',
    name: 'Ramesh Patil',
    email: 'ramesh.patil@example.com',
    mobile: '9812345678',
    address: 'House No. 42, North Lane, Ward 3',
    role: 'CITIZEN',
    password: 'Citizen@123',
    createdAt: '2026-01-15T09:30:00Z',
    unreadNotificationsCount: 2,
    totalComplaintsCount: 3,
  },
  {
    id: 'usr-cit-2',
    name: 'Sunita Sharma',
    email: 'sunita.sharma@example.com',
    mobile: '9823456789',
    address: 'Plot 15, Near Gandhi Chowk, Ward 2',
    role: 'CITIZEN',
    password: 'Citizen@123',
    createdAt: '2026-01-20T10:15:00Z',
    unreadNotificationsCount: 1,
    totalComplaintsCount: 3,
  },
  {
    id: 'usr-cit-3',
    name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    mobile: '9834567890',
    address: 'Market Yard Road, Ward 5',
    role: 'CITIZEN',
    password: 'Citizen@123',
    createdAt: '2026-02-01T11:00:00Z',
    unreadNotificationsCount: 0,
    totalComplaintsCount: 2,
  },
  {
    id: 'usr-cit-4',
    name: 'Priya Kadam',
    email: 'priya.kadam@example.com',
    mobile: '9845678901',
    address: 'Near Zilla Parishad Primary School, Ward 4',
    role: 'CITIZEN',
    password: 'Citizen@123',
    createdAt: '2026-02-10T14:20:00Z',
    unreadNotificationsCount: 1,
    totalComplaintsCount: 2,
  },
  {
    id: 'usr-cit-5',
    name: 'Anand Deshmukh',
    email: 'anand.deshmukh@example.com',
    mobile: '9856789012',
    address: 'Temple Street, Ward 1',
    role: 'CITIZEN',
    password: 'Citizen@123',
    createdAt: '2026-02-15T16:45:00Z',
    unreadNotificationsCount: 0,
    totalComplaintsCount: 2,
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-001',
    complaintNumber: 'GP-2026-0001',
    userId: 'usr-cit-1',
    category: 'Road Issues',
    title: 'Deep potholes on main market connecting road',
    description: 'Multiple deep potholes have formed right after the recent rainfall near the vegetable market entrance. Two two-wheelers skidded yesterday. Urgent asphalt patch repair is needed.',
    location: 'Near Vegetable Market, Ward 3 Main Road',
    latitude: 18.5204,
    longitude: 73.8567,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80',
    status: 'RESOLVED',
    assignedDepartment: 'Road Maintenance',
    assignedStaff: 'Mahesh Jadhav (Junior Engineer)',
    submittedAt: '2026-09-25T09:15:00Z',
    updatedAt: '2026-10-05T16:30:00Z',
    resolvedAt: '2026-10-05T16:30:00Z',
    user: {
      id: 'usr-cit-1',
      name: 'Ramesh Patil',
      email: 'ramesh.patil@example.com',
      mobile: '9812345678',
      address: 'House No. 42, North Lane, Ward 3',
    },
    statusHistory: [
      { id: 'sh-1', complaintId: 'cmp-001', status: 'SUBMITTED', remarks: 'Complaint submitted by citizen via Digital Portal.', changedBy: 'Ramesh Patil', createdAt: '2026-09-25T09:15:00Z' },
      { id: 'sh-2', complaintId: 'cmp-001', status: 'UNDER_REVIEW', remarks: 'Verified by Panchayat Inspector. Site inspection scheduled.', changedBy: 'Rajesh Shinde', createdAt: '2026-09-26T11:00:00Z' },
      { id: 'sh-3', complaintId: 'cmp-001', status: 'ASSIGNED', remarks: 'Assigned to Road Maintenance team with high priority.', changedBy: 'Rajesh Shinde', createdAt: '2026-09-27T10:30:00Z' },
      { id: 'sh-4', complaintId: 'cmp-001', status: 'IN_PROGRESS', remarks: 'Asphalt cold mix and bitumen gravel work underway.', changedBy: 'Mahesh Jadhav', createdAt: '2026-10-01T14:00:00Z' },
      { id: 'sh-5', complaintId: 'cmp-001', status: 'RESOLVED', remarks: 'Potholes fully filled and road leveling completed and certified.', changedBy: 'Mahesh Jadhav', createdAt: '2026-10-05T16:30:00Z' },
    ],
    feedback: {
      id: 'fb-1',
      complaintId: 'cmp-001',
      userId: 'usr-cit-1',
      rating: 5,
      comment: 'Very fast and clean work. The road is safe for motorcycles and auto-rickshaws now. Thank you!',
      createdAt: '2026-10-06T10:00:00Z',
    },
  },
  {
    id: 'cmp-002',
    complaintNumber: 'GP-2026-0002',
    userId: 'usr-cit-2',
    category: 'Street Light Problems',
    title: 'Flickering solar street lights outside Primary Health Center',
    description: 'Three consecutive street lights outside the PHC hospital gate have been flickering or completely blacked out for the past 4 nights. Patients arriving at night face severe visibility issues.',
    location: 'Primary Health Center Gate, Gandhi Chowk, Ward 2',
    latitude: 18.5245,
    longitude: 73.8512,
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=800&auto=format&fit=crop&q=80',
    status: 'RESOLVED',
    assignedDepartment: 'Street Lighting',
    assignedStaff: 'Suresh Patil (Electrical Line Worker)',
    submittedAt: '2026-09-23T18:40:00Z',
    updatedAt: '2026-10-02T17:15:00Z',
    resolvedAt: '2026-10-02T17:15:00Z',
    user: {
      id: 'usr-cit-2',
      name: 'Sunita Sharma',
      email: 'sunita.sharma@example.com',
      mobile: '9823456789',
      address: 'Plot 15, Near Gandhi Chowk, Ward 2',
    },
    statusHistory: [
      { id: 'sh-6', complaintId: 'cmp-002', status: 'SUBMITTED', remarks: 'Complaint submitted by citizen.', changedBy: 'Sunita Sharma', createdAt: '2026-09-23T18:40:00Z' },
      { id: 'sh-7', complaintId: 'cmp-002', status: 'UNDER_REVIEW', remarks: 'Checked with electrical maintenance log.', changedBy: 'Rajesh Shinde', createdAt: '2026-09-24T10:00:00Z' },
      { id: 'sh-8', complaintId: 'cmp-002', status: 'ASSIGNED', remarks: 'Line worker Suresh Patil assigned with replacement battery modules.', changedBy: 'Rajesh Shinde', createdAt: '2026-09-25T09:45:00Z' },
      { id: 'sh-9', complaintId: 'cmp-002', status: 'IN_PROGRESS', remarks: 'Batteries and LED fixture driver being replaced.', changedBy: 'Suresh Patil', createdAt: '2026-09-29T15:00:00Z' },
      { id: 'sh-10', complaintId: 'cmp-002', status: 'RESOLVED', remarks: 'Solar batteries replaced and new 60W LED fixtures tested successfully.', changedBy: 'Suresh Patil', createdAt: '2026-10-02T17:15:00Z' },
    ],
    feedback: {
      id: 'fb-2',
      complaintId: 'cmp-002',
      userId: 'usr-cit-2',
      rating: 4,
      comment: 'Lights are working very brightly now. Safe for night commuters.',
      createdAt: '2026-10-03T09:20:00Z',
    },
  },
  {
    id: 'cmp-003',
    complaintNumber: 'GP-2026-0003',
    userId: 'usr-cit-3',
    category: 'Water Supply Issues',
    title: 'Underground drinking water pipeline fracture & leakage',
    description: 'The main 4-inch drinking water feeder pipeline has fractured near house #18. Clean water is bubbling onto the street for 2 hours during morning supply hours, causing low pressure downstream.',
    location: 'Lane 4, Market Yard, Ward 5',
    latitude: 18.519,
    longitude: 73.862,
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186f5f7?w=800&auto=format&fit=crop&q=80',
    status: 'IN_PROGRESS',
    assignedDepartment: 'Water Supply',
    assignedStaff: 'Kishore Bhende (Water Works Supervisor)',
    submittedAt: '2026-10-02T07:30:00Z',
    updatedAt: '2026-10-05T12:00:00Z',
    resolvedAt: null,
    user: {
      id: 'usr-cit-3',
      name: 'Vikram Singh',
      email: 'vikram.singh@example.com',
      mobile: '9834567890',
      address: 'Market Yard Road, Ward 5',
    },
    statusHistory: [
      { id: 'sh-11', complaintId: 'cmp-003', status: 'SUBMITTED', remarks: 'Complaint registered by citizen.', changedBy: 'Vikram Singh', createdAt: '2026-10-02T07:30:00Z' },
      { id: 'sh-12', complaintId: 'cmp-003', status: 'UNDER_REVIEW', remarks: 'Water works dept notified immediately to halt morning pump cycle.', changedBy: 'Rajesh Shinde', createdAt: '2026-10-02T10:00:00Z' },
      { id: 'sh-13', complaintId: 'cmp-003', status: 'ASSIGNED', remarks: 'Assigned to emergency repair squad.', changedBy: 'Rajesh Shinde', createdAt: '2026-10-03T08:30:00Z' },
      { id: 'sh-14', complaintId: 'cmp-003', status: 'IN_PROGRESS', remarks: 'Excavation completed, pipe replacement collar clamp installation underway.', changedBy: 'Kishore Bhende', createdAt: '2026-10-05T12:00:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'cmp-004',
    complaintNumber: 'GP-2026-0004',
    userId: 'usr-cit-4',
    category: 'Drainage & Sanitation',
    title: 'Overflowing storm drainage canal near Zilla Parishad school',
    description: 'The open storm drain near the primary school boundary wall is choked with plastic and silt. Foul smell and water spilling onto the pedestrian walkway where school children walk daily.',
    location: 'Boundary Wall, Zilla Parishad Primary School, Ward 4',
    latitude: 18.528,
    longitude: 73.859,
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80',
    status: 'IN_PROGRESS',
    assignedDepartment: 'Sanitation',
    assignedStaff: 'Deepak Kale (Sanitation Inspector)',
    submittedAt: '2026-09-30T11:20:00Z',
    updatedAt: '2026-10-05T15:45:00Z',
    resolvedAt: null,
    user: {
      id: 'usr-cit-4',
      name: 'Priya Kadam',
      email: 'priya.kadam@example.com',
      mobile: '9845678901',
      address: 'Near Zilla Parishad Primary School, Ward 4',
    },
    statusHistory: [
      { id: 'sh-15', complaintId: 'cmp-004', status: 'SUBMITTED', remarks: 'Complaint lodged by citizen.', changedBy: 'Priya Kadam', createdAt: '2026-09-30T11:20:00Z' },
      { id: 'sh-16', complaintId: 'cmp-004', status: 'UNDER_REVIEW', remarks: 'Health hazard near school campus flagged as priority.', changedBy: 'Rajesh Shinde', createdAt: '2026-10-01T09:15:00Z' },
      { id: 'sh-17', complaintId: 'cmp-004', status: 'ASSIGNED', remarks: 'Sanitation team deployed with suction machine and silt desilting crew.', changedBy: 'Rajesh Shinde', createdAt: '2026-10-02T14:00:00Z' },
      { id: 'sh-18', complaintId: 'cmp-004', status: 'IN_PROGRESS', remarks: 'Desilting 120 meters of drain in progress. 60% silt removed.', changedBy: 'Deepak Kale', createdAt: '2026-10-05T15:45:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'cmp-005',
    complaintNumber: 'GP-2026-0005',
    userId: 'usr-cit-5',
    category: 'Waste Management',
    title: 'Weekly market garbage accumulation left uncollected',
    description: 'The weekly farmers market was held on Saturday and huge piles of vegetable waste and packing boxes were dumped near the ancient temple banyan tree. Stray cattle and dogs are scattering waste.',
    location: 'Behind Maruti Temple, Ward 1',
    latitude: 18.514,
    longitude: 73.854,
    imageUrl: null,
    status: 'ASSIGNED',
    assignedDepartment: 'Waste Management',
    assignedStaff: 'Santosh Gaikwad (Sanitation Supervisor)',
    submittedAt: '2026-10-04T14:10:00Z',
    updatedAt: '2026-10-06T10:30:00Z',
    resolvedAt: null,
    user: {
      id: 'usr-cit-5',
      name: 'Anand Deshmukh',
      email: 'anand.deshmukh@example.com',
      mobile: '9856789012',
      address: 'Temple Street, Ward 1',
    },
    statusHistory: [
      { id: 'sh-19', complaintId: 'cmp-005', status: 'SUBMITTED', remarks: 'Complaint submitted by citizen.', changedBy: 'Anand Deshmukh', createdAt: '2026-10-04T14:10:00Z' },
      { id: 'sh-20', complaintId: 'cmp-005', status: 'UNDER_REVIEW', remarks: 'Inspected by sanitary supervisor.', changedBy: 'Rajesh Shinde', createdAt: '2026-10-05T11:00:00Z' },
      { id: 'sh-21', complaintId: 'cmp-005', status: 'ASSIGNED', remarks: 'Tractor trailer scheduled for morning pickup.', changedBy: 'Rajesh Shinde', createdAt: '2026-10-06T10:30:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'cmp-006',
    complaintNumber: 'GP-2026-0006',
    userId: 'usr-cit-1',
    category: 'Public Facilities',
    title: 'Broken handpump cylinder handle causing injury hazard',
    description: 'The public community handpump near the community hall has a cracked cast-iron handle that slipped off while a villager was pumping water. Needs urgent replacement of mechanical assembly.',
    location: 'Community Hall Courtyard, Ward 3',
    latitude: 18.522,
    longitude: 73.858,
    imageUrl: null,
    status: 'UNDER_REVIEW',
    assignedDepartment: null,
    assignedStaff: null,
    submittedAt: '2026-10-05T16:00:00Z',
    updatedAt: '2026-10-06T14:00:00Z',
    resolvedAt: null,
    user: {
      id: 'usr-cit-1',
      name: 'Ramesh Patil',
      email: 'ramesh.patil@example.com',
      mobile: '9812345678',
      address: 'House No. 42, North Lane, Ward 3',
    },
    statusHistory: [
      { id: 'sh-22', complaintId: 'cmp-006', status: 'SUBMITTED', remarks: 'Complaint registered.', changedBy: 'Ramesh Patil', createdAt: '2026-10-05T16:00:00Z' },
      { id: 'sh-23', complaintId: 'cmp-006', status: 'UNDER_REVIEW', remarks: 'Estimating cost of new standard Mark-II handpump handle.', changedBy: 'Rajesh Shinde', createdAt: '2026-10-06T14:00:00Z' },
    ],
    feedback: null,
  },
  {
    id: 'cmp-007',
    complaintNumber: 'GP-2026-0007',
    userId: 'usr-cit-2',
    category: 'Water Supply Issues',
    title: 'Contaminated tap water supply with muddy sedimentation',
    description: 'For the last 2 days the piped tap supply between 6 AM and 8 AM is coming out yellow and muddy. Multiple households in Ward 2 reported stomach upsets. Requesting immediate water testing and chlorination.',
    location: 'Ward 2 Residential Area, Gandhi Chowk East',
    latitude: 18.525,
    longitude: 73.853,
    imageUrl: null,
    status: 'SUBMITTED',
    assignedDepartment: null,
    assignedStaff: null,
    submittedAt: '2026-10-06T08:30:00Z',
    updatedAt: '2026-10-06T08:30:00Z',
    resolvedAt: null,
    user: {
      id: 'usr-cit-2',
      name: 'Sunita Sharma',
      email: 'sunita.sharma@example.com',
      mobile: '9823456789',
      address: 'Plot 15, Near Gandhi Chowk, Ward 2',
    },
    statusHistory: [
      { id: 'sh-24', complaintId: 'cmp-007', status: 'SUBMITTED', remarks: 'Urgent complaint registered by citizen.', changedBy: 'Sunita Sharma', createdAt: '2026-10-06T08:30:00Z' },
    ],
    feedback: null,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'ntf-1',
    userId: 'usr-cit-1',
    complaintId: 'cmp-001',
    title: 'Complaint Resolved',
    message: 'Your complaint GP-2026-0001 (Road Issues) has been marked as RESOLVED. Please provide your valuable feedback.',
    read: false,
    createdAt: '2026-10-05T16:30:00Z',
  },
  {
    id: 'ntf-2',
    userId: 'usr-cit-1',
    complaintId: 'cmp-006',
    title: 'Complaint Under Review',
    message: 'Your complaint GP-2026-0006 is now UNDER REVIEW by the Panchayat Officer.',
    read: false,
    createdAt: '2026-10-06T14:00:00Z',
  },
  {
    id: 'ntf-3',
    userId: 'usr-admin-1',
    complaintId: 'cmp-007',
    title: 'New Urgent Complaint Submitted',
    message: 'New complaint GP-2026-0007 registered in Water Supply Issues category.',
    read: false,
    createdAt: '2026-10-06T08:30:00Z',
  },
];
